image: docker:19.03.1

stages:
  - build
  # - test
  - release
  # - deploy

variables:
  CONTAINER_BRANCH_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest


build:
  stage: build
  image: rustlang/rust:nightly-stretch
  script:
    - cargo +nightly build --release
  artifacts:
    paths:
      - ./target/release/video-streamer-rs

release:
  stage: release
  before_script:
    - df
    - cat /etc/resolv.conf
    - cat /etc/hosts
    - docker info
    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t $CONTAINER_BRANCH_IMAGE .
    - docker push $CONTAINER_BRANCH_IMAGE

