name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: actions-rs/components-nightly@v1
      run: cargo +nightly build --release --verbose
    - name: Run tests
      uses: actions-rs/components-nightly@v1
      run: cargo +nightly test --verbose
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: nozomi-video-streamer
        # Directory containing files to upload
        path: ./target/release/nozomi-video-streamer
